//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DocxFactory {

public class WordProcessingCompiler {
  public static void Compile(string p_srcFileName, string p_dstFileName) {
    WordProcessingCompilerPINVOKE.Compile(p_srcFileName, p_dstFileName);
    if (WordProcessingCompilerPINVOKE.SWIGPendingException.Pending) throw WordProcessingCompilerPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
